---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Simulation 95% CI coverage test for semiparametric CATE
```{r}
set.seed(100)

 passes <- c()
for(i in 1:100){
  print(i)
  formula <- ~ 1 + W1
  data_list <- sim.CATE(n=750, p=3,  sigma = NULL, formula_estimand = formula, formula_A = ~., formula_Y0W = ~ ., beta = c(1,0.5), beta_A = c(0,1,1,1), beta_Y = c(1,1,1,1)) 
  
  data <- data_list$data
  W <- data_list$W
  A <- data_list$A
  Y <- data_list$Y
  beta0 <- data_list$beta_CATE
  
  out <- causalGLM(formula, data, W, A, Y, estimand = "CATE", learning_method = "xgboost", verbose = FALSE)
  passes <- cbind(passes, out$coefs$lower <= beta0 & beta0 <= out$coefs$upper )
  print(rowMeans(passes))
}

```

```{R}
 data_list <- sim.OR(n=750, p=3, formula_estimand = formula, formula_A = ~., formula_Y0W = ~., beta = c(1,0.5), beta_A = 0.5*c(0,1,1,1), beta_Y = c(1,1,1,1)) 
  
  data <- data_list$data
data
log(data$OR) - 1 - data$W1*0.5
```

# Simulation 95% CI coverage test for semiparametric OR
```{r}
set.seed(41087880)

 passes <- c()
for(i in 1:20){
  print(i)
  formula <- ~ 1 + W1
  data_list <- sim.OR(n=750, p=2, formula_estimand = formula, formula_A = ~1, formula_Y0W = ~., beta = c(1,0.5), beta_A =0.5 , beta_Y = c(0,1,0)) 
  
  data <- data_list$data
  W <- data_list$W
  A <- data_list$A
  Y <- data_list$Y
  beta0 <- data_list$beta_logOR
  
  out <- causalGLM(formula, data, W, A, Y, estimand = "OR", learning_method = "glmnet",   sl3_Learner_A =   Lrnr_glm$new(family = binomial()),  sl3_Learner_Y =   Lrnr_glm$new(family = binomial()), verbose = T, delta_epsilon = 0.005)
 print(out$coefs)
  passes <- cbind(passes, out$coefs$lower <= beta0 & beta0 <= out$coefs$upper )
  print(rowMeans(passes))
}
```


# Simulation 95% CI coverage test for semiparametric RR
```{r}
set.seed(12630)
 passes <- c()
for(i in 1:100){
  print(i)
  formula <- ~ 1 + W1
  data_list <- sim.RR(n=500, p=3,   formula_estimand = formula, formula_A = ~., formula_Y0W = ~., beta = c(1,0.5), beta_A = c(0,1,1,1), beta_Y = c(1,1,1,1)) 
  
  data <- data_list$data
  W <- data_list$W
  A <- data_list$A
  Y <- data_list$Y
  beta0 <- data_list$beta_logRR
  
  out <- causalGLM(formula, data, W, A, Y, estimand = "RR", learning_method = "xgboost", verbose = FALSE)
  print(out$coefs)
  passes <- cbind(passes, out$coefs$lower <= beta0 & beta0 <= out$coefs$upper )
  print(rowMeans(passes))
}

```




# Simulation 95% CI coverage test for nonparametric CATE
```{r}
set.seed(12630)
 passes <- c()
for(i in 1:100){
  print(i)
  formula <- ~ 1 + W1
  data_list <- sim.CATE(n=750, p=3,  sigma = NULL, formula_estimand = formula, formula_A = ~., formula_Y0W = ~ ., beta = c(1,0.5), beta_A = c(0,1,1,1), beta_Y = c(1,1,1,1)) 
  
  data <- data_list$data
  W <- data_list$W
  A <- data_list$A
  Y <- data_list$Y
  beta0 <- data_list$beta_CATE
  
  out <- causalRobustGLM(formula, data, W, A, Y, estimand = "CATE", learning_method = "xgboost", verbose = FALSE)
  print(out$coefs)
  passes <- cbind(passes, out$coefs$lower <= beta0 & beta0 <= out$coefs$upper )
  print(rowMeans(passes))
}

```



