---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
devtools::install_github("tlverse/tmle3", ref = "general_submodels_devel" )
devtools::install_github("tlverse/sl3", ref = "Larsvanderlaan-formula_fix")
```


```{r}
devtools::document()

```

```{r}
passes<-c()
require(simcausal)
for(i in 1:200){
D <- DAG.empty()
D <- D + node("W1", distr = "runif",  min = -1, max = 1) + 
  node("W2", distr = "runif",  min = -1, max = 1) + 
   node("A", distr = "rbinom",  size = 1, prob = plogis(W1 + W2 )) +
  node("dNt", t = 1:10, EFU = TRUE , distr = "rbinom",  size = 1, prob = exp(0.5*A)*0.1*plogis(W1 + W2 + t)) +
  node("dCt", t = 1:10, EFU = TRUE,  distr = "rbinom",  size = 1, prob = 0.1*plogis(W1 + W2 + t)) 
D <- set.DAG(D)
data <- sim(D, n = 500)
data
data_N <- data[, grep("[d][N].+", colnames(data))]
data_C <- data[, grep("[d][C].+", colnames(data))]

data_surv <-  as.data.frame(do.call(rbind, lapply(1:nrow(data), function(i) {
  rowN <- data_N[i,]
  rowC <- data_C[i,]
  t <- which(rowN==1)
  tc <- which(rowC==1)
  if(length(tc)==0){
    tc <- 10
  }
  if(length(t)==0){
    t <- 12
  }
  Ttilde <- min(t,tc)
  Delta <- t <= tc
  return(matrix(c(Ttilde,Delta), nrow=1))
})))
colnames(data_surv) <- c("Ttilde", "Delta")
data$Ttilde <- data_surv$Ttilde
 data$Delta <- data_surv$Delta
 data <-  data[, -grep("[d][C].+", colnames(data))]
 data <-  data[, -grep("[d][N].+", colnames(data))]
  data
  
  out <- causalRobustCOXph(~1, data, learning_method = "xgboost", W = c("W1", "W2"), "A" = "A", Ttilde = "Ttilde", Delta = "Delta", formula_N = ~ . )
  passes <- c(passes, out$coefs$lower <= 0.5  & out$coefs$upper >= 0.5 )
  print(mean(passes))
}
```




```{r}
 
```

```{r}
n <- 1500
W <- replicate(3, runif(n, -1, 1))
A <- rbinom(n, 1, plogis(rowSums(W)))
T <- pmin(ceiling(rexp(n,  rate = exp(-1+A + rowMeans(W)))),10)
C <- pmin(ceiling(rexp(n,  rate = exp(-1.5+A + rowMeans(W)))),10)
Ttilde <- pmin(T,C)
Delta <- as.numeric(T <= C)
data <- data.table(W,A,Ttilde, Delta)
data
out <- causalRobustCOXph(~1, data, learning_method = "xgboost", W = c("V1", "V2", "V3"), "A" = "A", Ttilde = "Ttilde", Delta = "Delta", formula_Y = ~ . )
out
```


```{R}
vet_data <- read.csv("https://raw.githubusercontent.com/tlverse/deming2019-workshop/master/data/veteran.csv")
vet_data$trt <- vet_data$trt - 1
vet_data$time <- ceiling(vet_data$time / 20)
node_list <- list(
  W = c("celltype", "karno", "diagtime", "age", "prior"), A = "trt", T_tilde = "time", Delta = "status",
  time = "t", N = "N", A_c = "A_c", id = "X", pre_failure = "pre_failure"
)

out <- causalRobustCOXph(~1, vet_data, learning_method = "mars", W = "celltype", "A" = "trt", Ttilde = "time", Delta = "status")
out
```

```{r}
n <- 250
W <- runif(n, -1, 1)
A <- rbinom(n, size = 1, prob = plogis(W))
Y <-  rnorm(n, W + A , sd = 0.3)
data <- data.table(W,A,Y)
 
out <- causalGLM(~1, estimand = "CATE",  learning_method = "glm", data = data, W = "W", A = "A", Y = "Y")
out$tmle3_fit

Y <-  rbinom(n, size = 1, prob =   plogis(A + W))
data <- data.table(W,A,Y)
out <- causalGLM(~1, estimand = "OR",  learning_method = "glm", data = data, W = "W", A = "A", Y = "Y")
out$tmle3_fit

Y <-  rpois(n, exp(A+W))
data <- data.table(W,A,Y)
out <- causalGLM(~1, estimand = "RR",  learning_method = "glm", data = data, W = "W", A = "A", Y = "Y")
out$tmle3_fit
```


```{r}
n <- 250
W <- runif(n, -1, 1)
A <- rbinom(n, size = 1, prob = plogis(W))
Y <-  rnorm(n, W + A , sd = 0.3)
data <- data.table(W,A,Y)
 
out <- causalRobustGLM(~1, estimand = "CATE",  learning_method = "glm", data = data, W = "W", A = "A", Y = "Y")
out$coefs

Y <-   rnorm(n, W + A , sd = 0.3)
data <- data.table(W,A,Y)
out <- causalRobustGLM(~1, estimand = "CATT",  learning_method = "glm", data = data, W = "W", A = "A", Y = "Y")
out$coefs

Y <-   rbinom(n, size = 1, prob =  plogis(A + W))
data <- data.table(W,A,Y)
out <- causalRobustGLM(~1, estimand = "OR",  learning_method = "glm", data = data, W = "W", A = "A", Y = "Y")
out$coefs
```
